version: '3.8'

services:
  mariadb:
    image: mariadb:beta
    # Override command to set MySQL/MariaDB config parameters.
    # These flags help prevent aborted connections by increasing timeouts and packet sizes.
    command: >
      mysqld
      --max-allowed-packet=1G
      --net-read-timeout=10000
      --net-write-timeout=10000
      --wait_timeout=10000
      --interactive_timeout=10000
      --key_buffer_size=3G
      --innodb_buffer_pool_size=3G
      --query_cache_size=512M
      --query_cache_type=1
      --query_cache_limit=64M
      --innodb_log_file_size=1G
      --innodb_log_buffer_size=128M
      --innodb_flush_log_at_trx_commit=2
      --innodb_io_capacity=2000
      --innodb_flush_method=O_DIRECT
      --table_open_cache=2048
      --max_connections=10000
      --log-bin=mysql-bin
      --binlog_expire_logs_seconds=604800
      --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: sync_store
      MYSQL_USER: usex
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:8-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=123456
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
