version: '3.8'

services:
  # MariaDB Galera Node 1 (First node)
  mariadb1:
    image: mariadb:10.11
    command: >
      --wsrep_on=ON
      --wsrep_provider=/usr/lib/galera/libgalera_smm.so
      --wsrep_cluster_name=galera_cluster
      --wsrep_cluster_address=gcomm://mariadb1,mariadb2,mariadb3
      --wsrep_node_name=mariadb1
      --wsrep_node_address=mariadb1
      --wsrep_sst_method=mariabackup
      --wsrep_sst_auth=root:${MYSQL_ROOT_PASSWORD}
      --binlog_format=ROW
      --default-storage-engine=InnoDB
      --innodb_autoinc_lock_mode=2
      --innodb_flush_log_at_trx_commit=2
      # Performance optimizations from provided config
      --max-allowed-packet=1G
      --net-read-timeout=10000
      --net-write-timeout=10000
      --wait_timeout=10000
      --interactive_timeout=10000
      --key_buffer_size=3G
      --innodb_buffer_pool_size=3G
      --query_cache_size=512M
      --query_cache_type=1
      --query_cache_limit=64M
      --innodb_log_file_size=1G
      --innodb_log_buffer_size=128M
      --innodb_io_capacity=2000
      --innodb_flush_method=O_DIRECT
      --table_open_cache=2048
      --max_connections=10000
      --log-bin=mysql-bin
      --binlog_expire_logs_seconds=604800
      --skip-name-resolve
      # Additional performance optimizations
      --innodb_read_io_threads=8
      --innodb_write_io_threads=8
      --innodb_doublewrite=1
      --thread_cache_size=128
      --sort_buffer_size=16M
      --join_buffer_size=16M
      --tmp_table_size=128M
      --max_heap_table_size=128M
      --binlog_cache_size=4M
      --innodb_lru_scan_depth=100
      --innodb_file_per_table=1
      --innodb_stats_on_metadata=0
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: sync_store
      MYSQL_USER: usex
      MYSQL_PASSWORD: pass123
      MARIADB_AUTO_UPGRADE: "1"
      GALERA_NEW_CLUSTER: "1" # Only for first node during initial startup
    volumes:
      - mariadb1_cluster_data:/var/lib/mysql
    networks:
      - galera_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MariaDB Galera Node 2
  mariadb2:
    image: mariadb:10.11
    command: >
      --wsrep_on=ON
      --wsrep_provider=/usr/lib/galera/libgalera_smm.so
      --wsrep_cluster_name=galera_cluster
      --wsrep_cluster_address=gcomm://mariadb1,mariadb2,mariadb3
      --wsrep_node_name=mariadb2
      --wsrep_node_address=mariadb2
      --wsrep_sst_method=mariabackup
      --wsrep_sst_auth=root:${MYSQL_ROOT_PASSWORD}
      --binlog_format=ROW
      --default-storage-engine=InnoDB
      --innodb_autoinc_lock_mode=2
      --innodb_flush_log_at_trx_commit=2
      # Performance optimizations from provided config
      --max-allowed-packet=1G
      --net-read-timeout=10000
      --net-write-timeout=10000
      --wait_timeout=10000
      --interactive_timeout=10000
      --key_buffer_size=3G
      --innodb_buffer_pool_size=3G
      --query_cache_size=512M
      --query_cache_type=1
      --query_cache_limit=64M
      --innodb_log_file_size=1G
      --innodb_log_buffer_size=128M
      --innodb_io_capacity=2000
      --innodb_flush_method=O_DIRECT
      --table_open_cache=2048
      --max_connections=10000
      --log-bin=mysql-bin
      --binlog_expire_logs_seconds=604800
      --skip-name-resolve
      # Additional performance optimizations
      --innodb_read_io_threads=8
      --innodb_write_io_threads=8
      --innodb_doublewrite=1
      --thread_cache_size=128
      --sort_buffer_size=16M
      --join_buffer_size=16M
      --tmp_table_size=128M
      --max_heap_table_size=128M
      --binlog_cache_size=4M
      --innodb_lru_scan_depth=100
      --innodb_file_per_table=1
      --innodb_stats_on_metadata=0
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: sync_store
      MYSQL_USER: usex
      MYSQL_PASSWORD: pass123
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mariadb2_cluster_data:/var/lib/mysql
    networks:
      - galera_network
    restart: unless-stopped
    depends_on:
      - mariadb1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MariaDB Galera Node 3
  mariadb3:
    image: mariadb:10.11
    command: >
      --wsrep_on=ON
      --wsrep_provider=/usr/lib/galera/libgalera_smm.so
      --wsrep_cluster_name=galera_cluster
      --wsrep_cluster_address=gcomm://mariadb1,mariadb2,mariadb3
      --wsrep_node_name=mariadb3
      --wsrep_node_address=mariadb3
      --wsrep_sst_method=mariabackup
      --wsrep_sst_auth=root:${MYSQL_ROOT_PASSWORD}
      --binlog_format=ROW
      --default-storage-engine=InnoDB
      --innodb_autoinc_lock_mode=2
      --innodb_flush_log_at_trx_commit=2
      # Performance optimizations from provided config
      --max-allowed-packet=1G
      --net-read-timeout=10000
      --net-write-timeout=10000
      --wait_timeout=10000
      --interactive_timeout=10000
      --key_buffer_size=3G
      --innodb_buffer_pool_size=3G
      --query_cache_size=512M
      --query_cache_type=1
      --query_cache_limit=64M
      --innodb_log_file_size=1G
      --innodb_log_buffer_size=128M
      --innodb_io_capacity=2000
      --innodb_flush_method=O_DIRECT
      --table_open_cache=2048
      --max_connections=10000
      --log-bin=mysql-bin
      --binlog_expire_logs_seconds=604800
      --skip-name-resolve
      # Additional performance optimizations
      --innodb_read_io_threads=8
      --innodb_write_io_threads=8
      --innodb_doublewrite=1
      --thread_cache_size=128
      --sort_buffer_size=16M
      --join_buffer_size=16M
      --tmp_table_size=128M
      --max_heap_table_size=128M
      --binlog_cache_size=4M
      --innodb_lru_scan_depth=100
      --innodb_file_per_table=1
      --innodb_stats_on_metadata=0
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: sync_store
      MYSQL_USER: usex
      MYSQL_PASSWORD: pass123
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mariadb3_cluster_data:/var/lib/mysql
    networks:
      - galera_network
    restart: unless-stopped
    depends_on:
      - mariadb1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:rc-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "3306:3306"  # MySQL/MariaDB port
      - "8404:8404"  # HAProxy stats page
    networks:
      - galera_network
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3
    restart: unless-stopped

networks:
  galera_network:
    driver: bridge

volumes:
  mariadb1_cluster_data:
  mariadb2_cluster_data:
  mariadb3_cluster_data:
